# Generated by Django X.Y on 2023-04-19 09:22
from django.db import migrations
from django.core.management import call_command
from django.db.migrations import Migration


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    def load_fixture_data(self):
        call_command("loaddata", "fixture_data.json")

    def forwards(self, apps, schema_editor):
        self.load_fixture_data()

    def backwards(self, apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(
            code=Migration.load_fixture_data,
            reverse_code=Migration.backwards,
        ),
    ]
